### ISSUE TITLE
Version 2.0 Update

### ISSUE THREAD

**Issue by hemudi** [hemudi/hashtag_chonggong_creator#19]
## Todo
- [x] #21
- [x] Footer에 정보 추가
  - [x] 버전 추가
  - [ ] Github Link 추가
- [x] #20
  - [x] 테마 색상 변경
- [ ] 사이트 이름 변경
- [x] 모바일 대응 반응형 스타일 수정
